version: '5.1.3'

services:

  # ── Kafka infra ──────────────────────────────────────────────────────────────
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME:   2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID:                        1
      KAFKA_ZOOKEEPER_CONNECT:                zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS:             PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE:        "true"

  # ── Microservices ────────────────────────────────────────────────────────────
  account-service:
    build: ./account-service
    ports: ["50051:50051"]
    environment:
      PORT:         50051
      KAFKA_BROKER: kafka:9092
    depends_on: [kafka]
    volumes: [account-data:/app/data]

  transaction-service:
    build: ./transaction-service
    ports: ["50052:50052"]
    environment:
      PORT:         50052
      KAFKA_BROKER: kafka:9092
      ACCOUNT_HOST: account-service:50051
    depends_on: [kafka, account-service]
    volumes: [transaction-data:/app/data]

  notification-service:
    build: ./notification-service
    ports: ["50053:50053"]
    environment:
      PORT:         50053
      KAFKA_BROKER: kafka:9092
    depends_on: [kafka]
    volumes: [notification-data:/app/data]

  # ── Gateway ───────────────────────────────────────────────────────────────────
  api-gateway:
    build: ./api-gateway
    ports: ["3000:3000"]
    environment:
      PORT:              3000
      ACCOUNT_HOST:      account-service:50051
      TRANSACTION_HOST:  transaction-service:50052
      NOTIFICATION_HOST: notification-service:50053
    depends_on:
      - account-service
      - transaction-service
      - notification-service

volumes:
  account-data:
  transaction-data:
  notification-data:
