syntax = "proto3";
package account;

service AccountService {
  rpc CreateAccount    (CreateAccountRequest)  returns (AccountResponse);
  rpc GetAccount       (GetAccountRequest)     returns (AccountResponse);
  rpc ListAccounts     (ListAccountsRequest)   returns (AccountListResponse);
  rpc UpdateBalance    (UpdateBalanceRequest)  returns (AccountResponse);
  rpc DeleteAccount    (DeleteAccountRequest)  returns (AccountResponse);
}

message CreateAccountRequest {
  string owner   = 1;
  string type    = 2;
  double balance = 3;
}

message GetAccountRequest {
  string id = 1;
}

message ListAccountsRequest {
  string owner = 1;
}

message UpdateBalanceRequest {
  string id        = 1;
  double amount    = 2;
  string operation = 3;
}

message DeleteAccountRequest {
  string id = 1;
}

message AccountResponse {
  string id         = 1;
  string owner      = 2;
  string type       = 3;
  double balance    = 4;
  string status     = 5;
  string created_at = 6;
  string error      = 7;
}

message AccountListResponse {
  repeated AccountResponse accounts = 1;
  string error = 2;
}
